export const tableActionTypes = {
  SAVE_TABLE_RESIZE_COL_VALUES: 'SAVE_TABLE_RESIZE_COL_VALUES',
  SAVE_TABLE_RESIZE_ROW_VALUES: 'SAVE_TABLE_RESIZE_ROW_VALUES',
  SAVE_TABLE_CELL_DATA: 'SAVE_TABLE_CELL_DATA',
  SET_TARGET_CELL_ID: 'SET_TARGET_CELL_ID',
};

export const formulaActionTypes = {
  SET_FORMULA_TEXT: 'SET_FORMULA_TEXT',
};
